"""add_dnd_settings_to_users

Revision ID: c7f3a8b9d2e1
Revises: bac0db213528
Create Date: 2025-12-08 10:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f3a8b9d2e1'
down_revision = 'bac0db213528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dnd_start_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('dnd_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dnd_end_time')
    op.drop_column('users', 'dnd_start_time')
    # ### end Alembic commands ###

