"""add_expire_time_hours_to_notifications

Revision ID: bac0db213528
Revises: 156cbac98895
Create Date: 2025-12-07 15:11:36.331208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac0db213528'
down_revision = '156cbac98895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('expire_time_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'expire_time_hours')
    # ### end Alembic commands ###

